LLM_MODEL = "gpt-4o-mini"
DEFAULT_TEMPERATURE = 0.2
PLANNER_TEMPERATURE = 0
SYNTHESISER_TEMPERATURE = 0
REPORTER_TEMPERATURE = 0.1

EMBEDDING_MODEL = "all-MiniLM-L6-v2"
EMBEDDING_PROMPT_PREFIX = "Represent this sentence for retrieval: "